### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by key2long** [yuweijiang/HGL-pytorch#1]
Hello, this is a wonderful work.But i don't see the cvm model.I wnat to know how to extract features from pictures

**Comment by yuweijiang** [comment]
Hi xiaolong, Thanks for your attention. The cvm module is in the utils folder, thanks.

**Comment by yuweijiang** [comment]
We utilize the resnet-50 with labeled bounding boxes to extract proposal from pictures. More details can be seen in detector.py
